### ISSUE TITLE
PUT to S3 bucket it not forwarded (its forwarded as a GET)

### ISSUE THREAD

**Issue by tomlarkworthy** [markusahlstrand/cloudworker-proxy#119]
Love the proxy. I want to use it to mediate writes to S3, but it seems to be overfitted to the GET use-case.

I am am happy to open a PR if you are happy to merge it.

What I am trying to acheive is explained on my demo proxy: https://mps3-proxy.endpointservices.workers.dev/

**Comment by markusahlstrand** [comment]
Yes, happy to merge any PR's :)
Think this project is due for a bit of renovation..

**Comment by tomlarkworthy** [comment]
ok fixed in https://github.com/markusahlstrand/cloudworker-proxy/pull/120, the method needs to come from the ctx.request.method, not the ctx.method

**Comment by markusahlstrand** [comment]
Approved :)
