### ISSUE TITLE
Mocha tests are not run as TS properly

### ISSUE THREAD

**Issue by tomlarkworthy** [markusahlstrand/cloudworker-proxy#126]
After adding bun to the test runner, which has the ability to run TS without compilation, I noticed the mocha test are still not really being executed as TS. Probably this has something to do with the way they are run. Not really sure the best solution. With bun we could use `bun test` which has inbuilt Jest support.
Options: 
- fiddle with mocha to get it working 
- migrate to Jest
- rollback bun and use `tsc`

**Comment by markusahlstrand** [comment]
I think a jest migration should be pretty fast..

**Comment by tomlarkworthy** [comment]
it was super fast `bun test` ran everything out of the box except before had to be changed to beforeEach see https://github.com/markusahlstrand/cloudworker-proxy/pull/125
