### ISSUE TITLE
Feature idea: multiple origins

### ISSUE THREAD

**Issue by aidansteele** [markusahlstrand/cloudworker-proxy#19]
Firstly: I love this project. I had a similar idea and it was wonderful to see someone has already thought of it and done a better job than I could 😄 

An idea I had was that a Lambda function could be deployed into multiple regions. The Cloudflare worker would then direct requests to the **nearest** region for minimal latency. Perhaps additionally, if Lambda goes down in one region it could fall back to the second-nearest region, etc.

What do you think? Would this be useful?

**Comment by markusahlstrand** [comment]
Thanks for the feature idea!

Think there's a few ways this could be done. One way way would be to add Geo as a filtering parameter to the router. That way any hanlder could be applied to a specific county or region thanks to that Cloudflare adds a country header to each request.
The think this solution wouldn't solve would be the fallback part. Maybe we could add a circuit breaker handler at some point which disables handlers that fail calls and fall through to the next matching handlers?
Would this be a good solution for your use case?

**Comment by markusahlstrand** [comment]
@aidansteele This issue was closed by the last merge.. Do you think the geo functionality added works for you? If not feel free to reopen the issue
