### ISSUE TITLE
Adding multiple custom handlers?

### ISSUE THREAD

**Issue by stammy** [markusahlstrand/cloudworker-proxy#73]
Hey there, thanks for making this project! I just dug into Cloudflare workers for the first time yesterday and already have a little API proxy. One thing I couldn't figure out - and maybe I'm approaching this incorrectly - is how I can add more than one custom handler? I have a custom one working that I added with your example of new Proxy(config, { /* custom handler*/ }, but I was unable to format that to add more than one custom handler.

I would like to have a few custom handlers for a few distinct API endpoints that need different logic. I could do it all in one handler but wanted to abstract things out a bit for readability.

**Comment by stammy** [comment]
Related - is it possible to set separate rateLimits for custom handlers within the same proxy? For example, I have one api endpoint that should have a very high limit while another needs a more sane limit.

**Comment by markusahlstrand** [comment]
Hi @stammy, happy that you got it up and running.

Reading the docs I realize that it's not very clear how it works.. Basically it matches the name of the rule with the property name if that makes any sense. Maybe easier to understand with a sample: 

```
const handlers = {
  custom1: (options) => {
    return async (ctx) => {
      ctx.status = 200;
      ctx.body = 'Custom handler';
    };
  },
  custom2: (options) => {
    return async (ctx) => {
      ctx.status = 200;
      ctx.body = 'Custom handler 1';
    };
  },
}

const rules = [
  {
    handlerName: 'custom1',
    path: '/custom1',
  },
  {
    handlerName: 'custom2',
    path: '/custom2',
  },
]

const proxy = new Proxy(rules, handlers);
```

**Comment by markusahlstrand** [comment]
Yes, it should work fine to have separate ratelimits for different paths.

```
rules = [
  {
    handlerName: 'rateLimit',
    path: '/api/.*',
    options: {
        limit: 1,
        scope: 'low',
        type: 'IP', // Anything except IP will sum up all calls
    }
  },
  {
    handlerName: 'rateLimit',
    path: '/index.html',
    options: {
        limit: 100000, // The default allowed calls
        scope: 'high',
        type: 'IP', // Anything except IP will sum up all calls
    }
  }
];
```

I haven't tested the config about but it _should_ work :)

**Comment by stammy** [comment]
Awesome thanks - got everything I wanted working now!
